### ISSUE TITLE
How to run only one test

### ISSUE THREAD

**Issue by sporto** [lpil/gleeunit#1]
Hi

I would like to run only a subset of tests. 
e.g. one test or all tests for one module

With rebar3 it was something like `rebar3 eunit --module=day04_test`

It is possible with `gleam test`? How?

Thanks

**Comment by lpil** [comment]
`gleam test` will pass through any arguments, but `gleeunit` doesn't know how to do that yet. It would be a good feature to add for sure!

**Comment by lpil** [comment]
Closing as I think it's best to replace gleeunit with a more featureful package that isn't a thin wrapper in future.

**Comment by inoas** [comment]
https://hex.pm/packages/glacier_gleeunit or https://hex.pm/packages/glacier/ probably works as long as there is no better alternative
