### ISSUE TITLE
Separate halt logic

### ISSUE THREAD

**Issue by varnerac** [lpil/gleeunit#11]
`gleeunit` calls `erlang:halt/1` to [return an exit code](https://github.com/lpil/gleeunit/blob/main/src/gleeunit.gleam#L35-L39) for use in CI/CD pipelines.

I am currently using the scaffolded `foo_test.gleam`file module to start and stop the external systems. However, cleanup code after `gleeunit.main()` doesn't run because of the halt. Could have the scaffolded code look like t

```
gleeunit.main() |> gleeunit.halt()
```

This would allow folks to break the two apart,  adding cleanup code between two functions before a halt.

**Comment by lpil** [comment]
I would be open to having an additional function that returned a result rather than halting. `gleeunit.run_tests` perhaps?

**Comment by varnerac** [comment]
That works. It'd make sense for `gleeunit.run_tests` to return `Result(Nil, Nil)` so we could wire our own halt in for CI/CD. Alternative

**Comment by lpil** [comment]
I forget how eunit works but if it returns info on the tests run, which failed, etc it would be good to return that in the error case.
