### ISSUE TITLE
Backport some Glacier changes into Gleeunit

### ISSUE THREAD

**Issue by inoas** [lpil/gleeunit#14]
Before opening a PR and doing a lot of work I wanted to know if you are up for (me) backporting some changes from Glacier to Gleeunit.

The changes in question would be about making gleeunit take a list of module names `gleeunit -- test/foo_test.gleam test/foo2_unit.gleam` and formatting outputs.

The changes are here mostly https://github.com/inoas/glacier/tree/main/src in the files still named `gleeunit*`.

My goal would be to remove all the inlined copies fo gleeunit out of glacier again and just make glacier depend on gleeunit.

**Comment by lpil** [comment]
Heya! This is a just a thin wrapper, any new functionality should go in a new alternative to gleeunit.

**Comment by inoas** [comment]
I don't plan on reeinventing gleeunit, though.

The only thing `gleeunit` and any other gleam unit testing framework would need to have in common for `glacier` to target it is for it to take a list of modules and just run these test modules instead of finding all test modules.

Also it needs to not halt on exit code 1.

Basically that's the changes I have done to gleeunit and I'd like to backport those. Would that be a welcome change?

**Comment by lpil** [comment]
As I said no new functionality is going to be added to this project. It is as it intends to be, there is to be no additional scope growth here.

**Comment by inoas** [comment]
I understand the stance but that means I have to copy over any changes made to `gleeunit` over time instead of referencing it. 

I had hoped to just add those two things and then if there is a new runner for glacier to work it only has to allow passing in test modules, but ok.
