### ISSUE TITLE
Error formatting breaks Unicode characters

### ISSUE THREAD

**Issue by Nicd** [lpil/gleeunit#16]
1. Create new project
2. Edit autogenerated test to:

```gleam
pub fn hello_world_test() {
  "ööö"
  |> should.equal("äää")
}
```

3. Run `gleam test`

Output:

```
  1) issue_test_test.hello_world_test: module 'issue_test_test'
     Values were not equal
     expected: "Ã¤Ã¤Ã¤"
          got: "Ã¶Ã¶Ã¶"
```

Expected output:

```
  1) issue_test_test.hello_world_test: module 'issue_test_test'
     Values were not equal
     expected: "äää"
          got: "ööö"
```

I suspect the reason is somewhere in the interplay of `string.inspect` and the gleeunit formatters, but I could not pinpoint it.

**Comment by fabjan** [comment]
I think the problem is in `gleeunit_progress.erl` using "~s" to format strings it displays.

```
10> io:format("~s~n", [<<"åäö"/utf8>>]). 
Ã¥Ã¤Ã¶
ok
11> io:format("~ts~n", [<<"åäö"/utf8>>]).
åäö
ok
```

**Comment by fabjan** [comment]
I tried a naive solution (search&replace all `~s` with `~ts` in gleeunit_progress.erl) and got nicer output:

![Skärmavbild 2023-01-22 kl  21 14 05](https://user-images.githubusercontent.com/33322/213938156-850fa57c-2202-4b3f-843f-8ac0be89df31.png)

But that global search&replace is overkill, only the strings for user input would need to be formatted with `~ts`, e.g. the color codes and stuff need not be.

It also assumes strings in Gleam are always implemented as utf8 binaries.

**Comment by JohnBjrk** [comment]
Nice catch @fabjan, I was also looking at the issue to suggest something similar. I think at least these two occurrences would be good to change:
```erlang
format_assertion_failure(Type, Props, I) when Type =:= assertEqual_failed
                                            ; Type =:= assertEqual  ->
    Expected = inspect(proplists:get_value(expected, Props)),
    Value = inspect(proplists:get_value(value, Props)),
    [indent(I, "Values were not equal~n", []),
     indent(I, "expected: ~s~n", [Expected]),
     indent(I, "     got: ~s", [Value])];

format_assertion_failure(Type, Props, I) when Type =:= assertNotEqual_failed
                                            ; Type =:= assertNotEqual ->
    Value = inspect(proplists:get_value(value, Props)),
    [indent(I, "Values were equal~n", []),
     indent(I, "expected: not ~s~n,", [Value]),
     indent(I, "     got: ~s", [Value])];
```

**Comment by fabjan** [comment]
a few more I think, any place that uses inspect at least. I can open a PR if no-one else started working of a fix.

**Comment by JohnBjrk** [comment]
> A few more I think, any place that uses inspect at least. I can open a PR if no-one else started working of a fix.

@fabjan I haven't started any work on this so if your up for the task please go ahead.
