### ISSUE TITLE
can't find eunit.hrl on elixir 1.15

### ISSUE THREAD

**Issue by srikanthkyatham** [lpil/gleeunit#22]
Hi 

I am not able to find the eunit.hrl when using gleeunit on elixir 1.15. 
After doing some digging I found that https://elixirforum.com/t/compiling-eredis-with-elixir-1-15-breaks-compilation/56612/7. 

According to Jose, :eunit needs to be added to the extra_applications of the mix.exs of the dependency, which is gleeunit/mix.exs file here. I was not able to find the mix.exs on this repo. 

Let me know what to do. I would be happy to open an PR.

**Comment by srikanthkyatham** [comment]
Hi

Yes indeed gleeunit, is not depending on the Elixir. I understand that. Even I thought so. I have created a standalone erlang application  using rebar3 and added eunit test cases. It works fine. So erlang installation is ruled out. It seems Elixir v1.15 has some dependency related changes, if an app is not mentioned in the mix.exs then its corresponding paths are loaded or fetched.  I have been using gleeunit from the elixir project 1.14 and it works fine. 

The issue is with Elixir v1.15 and its dependency path changes. At least this is my understanding so far. 

Now coming to gleeunit.  When I install the dependency via mix, the gleeunit dependency seems to have an mix.exs 
![Screenshot 2023-08-31 at 23 30 35](https://github.com/lpil/gleeunit/assets/4823891/1cc12e21-0778-469a-ae29-5398f3b545bd)

Its extra_applications needs to be like this 

`
  def application do
    [
      extra_applications: [:logger, :eunit]
    ]
  end

`

Currently its like this
`
  def application do
    [
      extra_applications: [:logger]
    ]
  end

`

**Comment by lpil** [comment]
Again, we don't use Mix or Elixir in any way here. There is no `mix.exs` in this project and the information you have about mix projects is unrelated to this project.

That doesn't look like the build directory of a Gleam project. Could you share how it was you added `gleeunit` to your project? Thank you.

**Comment by srikanthkyatham** [comment]
Hi 

I should have stated that I am using gleeunit from elixir project. It has been added as dependency like below in my mix.exs file

`
{:gleeunit, "~> 0.11", only: [:dev, :test], runtime: false},
`

**Comment by srikanthkyatham** [comment]
Hi

Seems that the issue is coming from mix_gleam
https://github.com/gleam-lang/mix_gleam/blob/main/lib/mix_gleam/config.ex

I should raise the ticket on it. Not here. Sorry for the trouble.

**Comment by srikanthkyatham** [comment]
I have opened a PR on mix_gleam https://github.com/gleam-lang/mix_gleam/pull/35
