### ISSUE TITLE
JS: test failure shows line number within function within should.gleam, not within failed test function

### ISSUE THREAD

**Issue by chuckwondo** [lpil/gleeunit#26]
When testing javascript code, a failing test function is correctly identified within the error message, but the indicated line number is a line number within `should.gleam`, not within the test code. This makes it difficult, if not impossible to tell which line within a test function is the failing test, when multiple "should" calls are made within a single test function.

Of course, one solution is to make only one "should" call within each test function, but that's not always feasible. When it's not feasible, determining exactly which line is causing the failure can be a bit frustrating, increasing debugging difficulty

The reason that this occurs is because the "should" functions makes use of `panic`, but during JS transpilation, that translates to constructing errors with the line number of the `panic`, which is in the "should" function, not within the test function. (I don't know if this is also the case for Erlang.)

**Comment by lpil** [comment]
This is unfortunately impossible on either target due to Gleam not having macros.

In future this module will be deprecated in favour of the `assert <expression>` syntax.
