### ISSUE TITLE
Ability to configure timeout

### ISSUE THREAD

**Issue by darky** [lpil/gleeunit#34]
Hello!
Seems, that default timeout is 5s and no possibility to change it somehow

**Comment by lpil** [comment]
Hello! You can use eunits regular test case API to configure it any way you want when running on Erlang. Please see the eunit documentation

**Comment by sbergen** [comment]
For anyone looking for this information, apparently this is the way to do it:
```gleam
import gleam/erlang/process
import gleeunit

pub fn main() {
  gleeunit.main()
}

pub type Timeout {
  Timeout(Float, fn() -> Nil)
}

// This will time out 100 ms, note that the trailing underscore is required
pub fn hello_world_test_() -> Timeout {
  Timeout(0.1, fn() { process.sleep(1000) })
}
```
