### ISSUE TITLE
Line number describe in fault code in the wrong line

### ISSUE THREAD

**Issue by lostbean** [lpil/gleeunit#37]
When the error is reported, the line of the failed test function is reported incorrectly (line 15 in this case):
<img width="495" alt="image" src="https://github.com/user-attachments/assets/0fd23ae5-3134-4229-b0fe-1bd6ca80d0fe">

The actual function is located on line 61 and there no subroutines from that function at the reported line 15. Actually, the line 15 is the closing scoping of the `main()` function. 
<img width="239" alt="image" src="https://github.com/user-attachments/assets/a68dba58-06bc-44f5-8b61-cb479a37145c">

**Comment by lpil** [comment]
EUnit uses Erlang line numbers so there's no way to make them match with Gleam ones.
