### ISSUE TITLE
JS: Show line information when a test fails at a todo or assignment failure

### ISSUE THREAD

**Issue by CrowdHailer** [lpil/gleeunit#4]
current output

```
❌ 
eyg/functions_test.call_generic_test: Error: This has not yet been implemented
```

**Comment by lpil** [comment]
Let's do this for sure

**Comment by inoas** [comment]
Once this gets done https://github.com/gleam-lang/gleam/issues/1501 there could be some cross usage to also show the test function name?

**Comment by lpil** [comment]
That change is not needed, we already have all the information required on the error. We just need to change the JavaScript to print it
