### ISSUE TITLE
Mix resolution problem

### ISSUE THREAD

**Issue by srikanthkyatham** [lpil/gleeunit#9]
Dependencies have diverged:
* gleam_stdlib (Hex package)
  the dependency gleam_stdlib in mix.exs is overriding a child dependency:

  > In mix.exs:
    {:gleam_stdlib, "~> 0.24", [env: :prod, repo: "hexpm", hex: "gleam_stdlib", compile: "gleam build", app: false]}

  > In deps/gleeunit/mix.exs:
    {:gleam_stdlib, "~> 0.19", [env: :prod, hex: "gleam_stdlib", repo: "hexpm", optional: false]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies

**Comment by lpil** [comment]
Could you expand upon the error? I'm not familiar with what Mix is doing here.

Gleeunit is compatible with gleam_stdlib 0.24, and that error prints compatible version constraints.
